name: Build ZMK firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      boards: |
        nice_nano_v2 corne_left
        nice_nano_v2 corne_right
